G2-图书管理系统-工程文件/mylibrary/library/urls.py
from django.urls import path
from library import views

urlpatterns = [
    path('mybooks/', views.LoanedBooksByUserListView.as_view(), name='my-borrowed'),

]

G2-图书管理系统-工程文件/mylibrary/mylibrary/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from library.views import index,BookListView,BookDetailView,AuthorListView
from  accounts.views import *
from library.views import SearchView,BorrowView,ReturnView
urlpatterns = [
    # path('/', include('accounts.urls'), name='index'),
    # path('',registerPage, name='register'),
    path('',index,name = 'index'),
    path('books/',BookListView.as_view(), name='books'),
    path('book/<int:pk>',BookDetailView.as_view(), name='book-detail'),
    path('authors/',AuthorListView.as_view(), name='authors'),

    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('search/', SearchView.as_view(), name='search'),
    path('borrow/', BorrowView.as_view(), name='borrow'),
    path('library/', include('library.urls')),

    path('return/', ReturnView.as_view(), name='return'),

    # path('login/', views.loginPage,name = 'login'),

]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

G2-图书管理系统-工程文件/mylibrary/library/models.py
from django.db import models
import uuid
# Create your models here.
from datetime import datetime, timedelta
from django.urls import reverse

from django.contrib.auth.models import User
from datetime import date

#定义图书模型:
#并添加字段定义（字段相当于数据库表中的列属性）
from django.views import generic


class Book(models.Model):
    #书名
    title = models.CharField(max_length=50)
    #作者
    author = models.ForeignKey('Author',on_delete=models.SET_NULL,null=True)
    is_aviliable = models.BooleanField(verbose_name='是否可借', default=True)

    #出版社
    pub = models.CharField(max_length=30)
    #概述
    summary = models.TextField(help_text='写一些对此书的概述吧')

    def __str__(self):
        return "<书名:%s>"%self.title#返回当前对象的书名，显示在管理页面上
    def get_absolute_url(self):
        """
        Returns the url to access a particular book instance.
        """
        return reverse('book-detail', args=[str(self.id)])
class Author(models.Model):

    name = models.CharField(max_length=100)
    # last_name = models.CharField(max_length=100)
    # date_of_birth = models.DateField(null=True, blank=True)
    # date_of_death = models.DateField('Died', null=True, blank=True)

    # def get_absolute_url(self):
    #     """
    #     Returns the url to access a particular author instance.
    #     """
    #     return reverse('author-detail', args=[str(self.id)])


    def __str__(self):
        """
        String for representing the Model object.
        """
        return '%s' % (self.name)

#图书的副本，用于定义此书籍是可借。预计的返还日期等信息
class BookInstance(models.Model):
    id = models.UUIDField(primary_key=True,default=uuid.uuid4)
    book = models.ForeignKey('Book',on_delete=models.SET_NULL,null=True)
    date_borrow = models.DateTimeField(null=True,blank=True)
    date_back = models.DateTimeField(null=True,blank=True)
    #书籍借阅状态
    LOAN_STATUS = (
        ('m', 'Maintenance(未上架)'),
        ('o', 'On loan(被借)'),
        ('a', 'Available(可借)'),
        # ('r', 'Reserved'),
    )
    status = models.CharField(max_length=1, choices=LOAN_STATUS, blank=True, default='m', help_text='Book availability')
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        """
        String for representing the Model object
        """
        return '%s (%s)' % (self.id,self.book.title)
    #根据返还日期排序
    class Meta:
        ordering = ["date_back"]

# @admin.register(BookInstance)
# class BookInstanceAdmin(admin.ModelAdmin):
#     list_display = ('book', 'status', 'borrower', 'due_back', 'id')
#     list_filter = ('status', 'due_back')
#
#     fieldsets = (
#         (None, {
#             'fields': ('book','imprint', 'id')
#         }),
#         ('Availability', {
#             'fields': ('status', 'due_back','borrower')
#         }),
#     )




#借的书籍是否逾期
# @property
def is_over_date(self):
    if self.date_back.replace(tzinfo = None) and datetime.now().replace(tzinfo=None)>self.date_back.replace(tzinfo = None):
        return True
    return False

G2-图书管理系统-工程文件/mylibrary/templates/authors.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
        	<link rel="stylesheet" href="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/css/bootstrap.min.css">
	<script src="https://cdn.staticfile.org/jquery/2.1.1/jquery.min.js"></script>
	<script src="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>
	<link href="https://cdn.bootcss.com/bootstrap/4.1.0/css/bootstrap.min.css" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="css/htmleaf-demo.css"><!--演示页面样式，使用时可以不引用-->
	<link rel="stylesheet" href="style.css">
    <title>Title</title>
</head>
<body>
{% extends "base_generic.html" %}

{% block content %}

     <h1>作者列表</h1>
	<div class="wrapper mt-4">
		    <div class="container">
		        <div class="row">
		            <div class="col-12">
		                <div class="jumbotron">
		                    <h1>你好！欢迎来到本校的线上图书馆！</h1>
		                    <p>目前藏书有{{ num_of_books }}册</p>
                            <p>涉及的国内外作者{{ num_of_authors }}人</p>
		                </div>
		            </div>
		        </div>
		        <div class="row">
                    {% if author_list %}
    <ul>

     {% for author in author_list %}
             <div class="col-md-6 col-lg-4">


		                <h2>{{ author.name }}</h2>
{#                        <h4> 作者:{{book.author}}</h4>#}
{#		                <p>本书概述：{{ book.summary }}</p>#}
{#		                <p><a class="btn btn-secondary" href="{{ book.get_absolute_url }}" role="button">查看详情 &raquo;</a></p>#}
{#                        <p>{{ book.get_absolute_url}}fgfg</p>#}
      <li>
      </li>
             </div>

      {% endfor %}

    </ul>
    {% else %}
      <p>There are no books in the library.</p>
    {% endif %}
		        </div>
		    </div>
		</div>

{% endblock %}

</body>
</html>

G2-图书管理系统-工程文件/mylibrary/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>

  {% block title %}<title>Local Library</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="/static/bootstrap-4.6.0-dist/css/bootstrap.min.css" rel="stylesheet">
<script src="/static/bootstrap-4.6.0-dist/js/bootstrap.min.js"></script>


<script src="/static/bootstrap-4.6.0-dist/jquery-3.4.1.js"></script>
<script src="/static/bootstrap-4.6.0-dist/popper.js"></script>

  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>

	<div class="htmleaf-container">
		<nav class="navbar navbar-expand-md navbar-dark bg-dark navbar-offcanvas">
		    <div class="container-fluid">
		        <a class="navbar-brand" href="#">Navbar</a>
		        <ul class="navbar-nav navbar-top">
		            <li class="nav-item active">
		                <a class="nav-link" href="{% url 'index' %}">Home <span class="sr-only">(current)</span></a>
		            </li>
		            <li class="nav-item">
		                <a class="nav-link" href={% url 'books' %}>所有书籍</a>
		            </li>
		            <li class="nav-item">
		                <a class="nav-link" href={% url 'authors' %}>所有作者</a>
		            </li>
		            <li class="nav-item dropdown">
		                <a class="nav-link dropdown-toggle" role="button" href="#!" id="dropdownExample" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">个人中心</a>
		                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownExample">
		                    <a class="dropdown-item" href="{% url 'my-borrowed' %}">个人主页</a>
		                    <a class="dropdown-item" href="{% url 'search' %}">找书/借书</a>
		                    <a class="dropdown-item" href="{% url 'my-borrowed' %}">还书</a>
		                </div>
		            </li>
		        </ul>
		        <button class="navbar-toggler navbar-toggler-right navbar-icon" type="button" data-toggle="collapse" data-target="#navbar-mobile" aria-controls="navbar-mobile" aria-expanded="false" aria-label="Toggle navigation">
		            <span class="icon-bar bar1"></span>
		            <span class="icon-bar bar2"></span>
		            <span class="icon-bar bar3"></span>
		        </button>
		        <div class="navbar-collapse collapse ml-auto" id="navbar-mobile">
		            <ul class="navbar-nav ml-auto">
		                <li class="nav-image">
		                    <img src="" alt="">
		                </li>
		                <li class="nav-item">
		                    <a href="{% url 'login' %}" class="nav-link">登录</a>
		                </li>
		                <li class="nav-item">
		                    <a href="{% url 'register' %}" class="nav-link">注册</a>
		                </li>
		                <li class="nav-item">
		                    <a href="#!" class="nav-link">Link</a>
		                </li>
		            </ul>
		        </div>
		    </div>
		</nav>
		<header class="htmleaf-header">
			<h1> <span></span></h1>
			<div class="htmleaf-links">
			</div>
		</header>
{% block content %}{% endblock %}



	</div>

</body>
</html>

G2-图书管理系统-工程文件/mylibrary/templates/book_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
        	<link rel="stylesheet" href="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/css/bootstrap.min.css">
	<script src="https://cdn.staticfile.org/jquery/2.1.1/jquery.min.js"></script>
	<script src="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>
	<link href="https://cdn.bootcss.com/bootstrap/4.1.0/css/bootstrap.min.css" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="css/htmleaf-demo.css"><!--演示页面样式，使用时可以不引用-->
	<link rel="stylesheet" href="style.css">
    <title>Title</title>
</head>
<body>
{% extends "base_generic.html" %}

{% block content %}

     <h1>书籍列表</h1>
	<div class="wrapper mt-4">
		    <div class="container">
		        <div class="row">
		            <div class="col-12">
		                <div class="jumbotron">
		                    <h1>你好！欢迎来到本校的线上图书馆！</h1>
		                    <p>目前藏书有{{ num_of_books }}册</p>
                            <p>涉及的国内外作者达{{ num_of_authors }}人</p>
		                </div>
		            </div>
		        </div>
		        <div class="row">
                    {% if book_list %}
    <ul>

     {% for book in book_list %}
             <div class="col-md-6 col-lg-4">


		                <h2>{{ book.title }}</h2>
                        <h4> 作者:{{book.author}}</h4>
		                <p>本书概述：{{ book.summary }}</p>
		                <p><a class="btn btn-secondary" href="{{ book.get_absolute_url }}" role="button">查看详情 &raquo;</a></p>
                        <p>{{ book.get_absolute_url}}fgfg</p>
      <li>
      </li>
             </div>

      {% endfor %}

    </ul>
    {% else %}
      <p>There are no books in the library.</p>
    {% endif %}
		        </div>
		    </div>
		</div>

{% endblock %}

</body>
</html>

G2-图书管理系统-工程文件/mylibrary/templates/bookinstance_list_borrowed_user.html
{#   {% if not user.is_authenticated %}#}
{##}
{#    <script>#}
{#           alert('请先登录')#}
{#        </script>#}
{#    {% endif %}#}
<!DOCTYPE html>
<html lang="zh">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title></title>
    	<link rel="stylesheet" href="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/css/bootstrap.min.css">
	<script src="https://cdn.staticfile.org/jquery/2.1.1/jquery.min.js"></script>
	<script src="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>
	<link href="https://cdn.bootcss.com/bootstrap/4.1.0/css/bootstrap.min.css" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="css/htmleaf-demo.css"><!--演示页面样式，使用时可以不引用-->
	<link rel="stylesheet" href="style.css">
</head>
<body>

{% extends "base_generic.html" %}

{% block content %}

   {% if user.is_authenticated %}
     <li>User: {{ user.get_username }}</li>
     <li><a href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>
{#   {% else %}#}
{#        <script>#}
{#           alert('请先登录')#}
{#        </script>#}
{#     <li><a href="{% url 'login'%}?next={{request.path}}">Login</a></li>#}
   {% endif %}



{#    <h1>Borrowed books</h1>#}
{##}
{#    {% if bookinstance_list %}#}
{#    <ul>#}
{##}
{#      {% for bookinst in bookinstance_list %}#}
{#      <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">#}
{#        <a href="{% url 'book-detail' bookinst.book.pk %}">{{bookinst.book.title}}</a> ({{ bookinst.date_back  }})#}
{#      </li>#}
{#      {% endfor %}#}
{#    </ul>#}
{##}
{#    {% else %}#}
{#      <p>当前没有已借阅书籍</p>#}
{#    {% endif %}#}


 <div class="col-sm-3 col-md-2 sidebar">
        <ul class="nav nav-sidebar">
            <li class="active"><a href="/home/">个人中心</a></li>
            <li><a href="/search/">借书</a></li>
        </ul>
    </div>
    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
        <h2 class="page-header">正在借阅</h2>
        <div class="table-responsive">
            <table class="table table-striped">
              <thead>
                <tr>
                  <th scope="col">#</th>
                  <th scope="col">书名</th>
                  <th scope="col">作者</th>
                  <th scope="col">出版社</th>
                  <th scope="col">借出时间</th>
                  <th scope="col">归还期限</th>
                  <th scope="col">操作</th>
                </tr>
              </thead>
              <tbody>
                {% for books in bookinstance_list %}
                    <tr>
                        <th scope="row">{{ forloop.counter }}</th>
                        <a href="{% url 'book-detail' books.book.pk %}"><td>{{ books.book.title }}</td></a>
                        <td>{{ books.book.author }}</td>
                        <td>{{ books.book.pub }}</td>
                        <td>{{ books.date_borrow }}</td>
                        <td>{{ books.date_back }}</td>
                        <td><a class="btn btn-primary btn-sm" href="/return/?book_id={{ books.book.id }}">还书</a></td>
                    </tr>
                {% endfor %}
              </tbody>
            </table>
        </div>
        {% if not bookinstance_list %}
            <h5 class="page-header" align="center">您当前没有借书记录</h5>
        {% endif %}
  {% if messages %}
              <script>
                  {% for msg in messages %}
                      alert('{{ msg.message }}');
                  {% endfor %}
              </script>
          {% endif %}
    </div>
{% endblock %}



</body>
</html>

G2-图书管理系统-工程文件/mylibrary/templates/index.html
<!DOCTYPE html>
<html lang="zh">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"> 
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title></title>
    	<link rel="stylesheet" href="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/css/bootstrap.min.css">
	<script src="https://cdn.staticfile.org/jquery/2.1.1/jquery.min.js"></script>
	<script src="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>
	<link href="https://cdn.bootcss.com/bootstrap/4.1.0/css/bootstrap.min.css" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="css/htmleaf-demo.css"><!--演示页面样式，使用时可以不引用-->
	<link rel="stylesheet" href="style.css">
</head>
<body>
{% extends "base_generic.html" %}

{% block content %}
		<div class="wrapper mt-4">
		    <div class="container">
		        <div class="row">
		            <div class="col-12">
		                <div class="jumbotron">
		                    <h1>你好！欢迎来到本校的线上图书馆！</h1>
		                    <p>目前藏书有{{ num_of_books }}册</p>
                            <p>涉及的国内外作者{{ num_of_authors }}人</p>
		                </div>
		            </div>
		        </div>
		        <div class="row">
		            <div class="col-md-6 col-lg-4">
		                <h2>Heading</h2>
		                <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.</p>
		                <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
		            </div>
		            <div class="col-md-6 col-lg-4">
		                <h2>Heading</h2>
		                <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.</p>
		                <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
		            </div>
		            <div class="col-md-6 col-lg-4">
		                <h2>Heading</h2>
		                <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.</p>
		                <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
		            </div>
		            <div class="col-md-6 col-lg-4">
		                <h2>Heading</h2>
		                <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.</p>
		                <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
		            </div>
		            <div class="col-md-6 col-lg-4">
		                <h2>Heading</h2>
		                <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.</p>
		                <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
		            </div>
		            <div class="col-md-6 col-lg-4">
		                <h2>Heading</h2>
		                <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.</p>
		                <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
		            </div>
		        </div>
		    </div>
		</div>
{% endblock %}


{#	<script src="/static/js/jquery.min.js" type="text/javascript"></script>#}
{#	<script src="https://cdn.bootcss.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>#}
{#	<script  src="js/index.js"></script>#}
</body>
</html>

G2-图书管理系统-工程文件/mylibrary/templates/search.html
<!DOCTYPE html>
<html lang="zh">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title></title>
    	<link rel="stylesheet" href="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/css/bootstrap.min.css">
	<script src="https://cdn.staticfile.org/jquery/2.1.1/jquery.min.js"></script>
	<script src="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>
	<link href="https://cdn.bootcss.com/bootstrap/4.1.0/css/bootstrap.min.css" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="css/htmleaf-demo.css"><!--演示页面样式，使用时可以不引用-->
	<link rel="stylesheet" href="style.css">
</head>
<body>

{% extends 'base_generic.html' %}
{% load static %}
{% block title %}借书{% endblock %}
{% block css %}<link href="{% static 'css/search.css' %}" rel="stylesheet"/>{% endblock %}

{% block content %}
       {% if user.is_authenticated %}
     <li>User: {{ user.get_username }}</li>
     <li><a href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>
{#   {% else %}#}
{#        <script>#}
{#           alert('请先登录')#}
{#        </script>#}
{#     <li><a href="{% url 'login'%}?next={{request.path}}">Login</a></li>#}
   {% endif %}
    <div class="col-sm-3 col-md-2 sidebar" xmlns="http://www.w3.org/1999/html" xmlns="http://www.w3.org/1999/html">
{#        <ul class="nav nav-sidebar">#}
{#            <li><a href="/home/">个人中心</a></li>#}
            <li class="active"><a href="/search/">借书</a></li>
{#        </ul>#}
    </div>
    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
        <div class="row placeholders">
            <form class="form-search" action="/search/" method="get">
                {% csrf_token %}

                <div class="form-group">
                    {{ search }}
                </div>
                <button type="submit" class="btn btn-primary btn-block">查询</button>
            </form>
        </div>
        <div class="table-responsive">
            <table class="table table-striped">
              <thead>
                <tr>
                  <th scope="col">#</th>
                  <th scope="col">书名</th>
                  <th scope="col">作者</th>
                  <th scope="col">出版社</th>
                  <th scope="col">操作</th>
                </tr>
              </thead>
              <tbody>
                {% for book in books %}
                    <tr>
                        <th scope="row">{{ forloop.counter }}</th>
                        <td>{{ book.title }}</td>
                        <td>{{ book.author }}</td>
                        <td>{{ book.pub }}</td>
                        {% if book.is_aviliable %}
                            <td><a class="btn btn-success btn-sm" href="/borrow/?book_id={{ book.id }}">借书</a></td>
                        {% else %}
                            <td>已借出</td>
                        {% endif %}
                    </tr>
                {% endfor %}
              </tbody>
            </table>
        </div>
        {% if message %}
          <div class="alert alert-warning">{{ message }}</div>
        {% endif %}
    </div>
{% endblock %}
</body>
</html>